version: '3.8'

# Caddy production configuration overlay
# Use with: docker compose -f docker-compose.yml -f docker-compose.caddy.yml up -d
#
# This configuration:
# - Removes Management API port exposure (Caddy handles HTTPS)
# - Connects services to your existing caddy_network

services:
  retro-aim-server:
    environment:
      # Make API accessible from all interfaces on caddy_network
      - API_LISTENER=0.0.0.0:8080
      # Override with production settings
      - DISABLE_AUTH=${DISABLE_AUTH:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "5190:5190"  # OSCAR (AIM/ICQ)
      - "9898:9898"  # TOC protocol
      # Management API port removed - only accessible via Caddy
      # - "8080:8080"
    networks:
      - aim-network
      - caddy_network

networks:
  # Internal network for AIM server
  aim-network:
    driver: bridge

  # Connect to existing Caddy network (for Management API)
  caddy_network:
    external: true
